---
title: "Time Series Analysis Final Project"
date: "2023-05-27"
output: html_document
---

```{r}
# 导入需要的包
packages = c("ggplot2", "dplyr", "tidyr", "data.table", 'corrplot', 'forecast', 'tseries','urca',
             'TSA', 'tibble', 'TTR', 'xts', 'assertthat','dygraphs','zoo','rugarch')

my.install <- function(pkg, ...){
if (!(pkg %in% installed.packages()[,1])) {
install.packages(pkg)
}
return (library(pkg, ...))
}
purrr::walk(packages, my.install, character.only = TRUE, warn.conflicts =
                FALSE)
```

```{r}
# 读取数据，经检查不存在缺失值------------------------------------------------------------------
all_index <- read.csv(file ="Indexes2013-2023.csv",sep=",")[239:2508,] # 剔除“数据来源：wind”
all_index$Date <- as.Date(all_index$Date, format = "%Y/%m/%d")
```

```{r}
# daily price data visualization
xts_list <- vector(mode="list", length=3)
xts50 = xts(all_index$SSE50, order.by=all_index$Date)
xts_list[['SSE50']] <- xts50
xts300 = xts(all_index$CSI300, order.by=all_index$Date)
xts_list[['CSI300']] <- xts300
xts500 = xts(all_index$CSI500, order.by=all_index$Date)
xts_list[['CSI500']] <- xts500
xts_table= do.call(cbind, xts_list)

dygraph(xts_table, xlab = "Time", ylab = "High value", main = "Time Series
") %>% dyRangeSelector()
```

```{r}
# 指数、日频月频收益率作图---------------------------------------------------------------------
# SSE50、收益率作图
year_pos = as.vector(unname(tapply(seq_along(all_index$Date), year(all_index$Date), function(x) min(x))))
year_labels = c("2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021","2022","2023")

n = 2270
d<-all_index$SSE50[1:n];d1<-all_index$SSE50[2:n]; d2<-all_index$SSE50[1:n-1]
ret_d50 = xts(diff(log(d)), order.by = all_index$Date[2:n])
ret_m50 = aggregate(ret_d50, as.yearmon, mean)
ps.options(horizontal=F, width=5, height=12, pointsize=14)
par(mar=c(2,4,1,1),mfrow=c(3,1), mgp=c(1.8,0.5,0))
plot(d, type='l', main='SSE50', ylab="Daily price", xaxt="n",xlab='',col="chartreuse4")
axis(1, at=year_pos,labels=year_labels)
plot(as.vector(unname(ret_d50)), type='l', ylab="Daily return", xaxt="n",xlab='year',col="cornflowerblue",ylim=c(-0.1,0.1))
axis(1, at=year_pos,labels=year_labels)
plot(ret_m50, type='l', ylab="Monthly return", xaxt="n",xlab='year',col="blue",ylim=c(-0.02,0.02))
axis(1, at=year_pos,labels=year_labels)

# CSI300、收益率作图
e<-all_index$CSI300[1:n];e1<-all_index$CSI300[2:n]; e2<-all_index$CSI300[1:n-1]
ret_d300 = xts(diff(log(e)), order.by = all_index$Date[2:n])
ret_m300 = aggregate(ret_d300, as.yearmon, mean)
ps.options(horizontal=F, width=5, height=12, pointsize=14)
par(mar=c(2,4,1,1),mfrow=c(3,1), mgp=c(1.8,0.5,0))
plot(e, type='l', main='CSI300', ylab="Daily price", xaxt="n",xlab='',col="cyan4")
axis(1, at=year_pos,labels=year_labels)
plot(as.vector(unname(ret_d300)), type='l', ylab="Daily return", xaxt="n",xlab='year',col="cornflowerblue",ylim=c(-0.1,0.1))
axis(1, at=year_pos,labels=year_labels)
plot(ret_m300, type='l', ylab="Monthly return", xaxt="n",xlab='year',col="blue",ylim=c(-0.02,0.02))
axis(1, at=year_pos,labels=year_labels)

# CSI500、收益率作图
f<-all_index$CSI500[1:n];f1<-all_index$CSI500[2:n]; f2<-all_index$CSI500[1:n-1]
ret_d500 = xts(diff(log(f)), order.by = all_index$Date[2:n])
ret_m500 = aggregate(ret_d500, as.yearmon, mean)
ps.options(horizontal=F, width=5, height=12, pointsize=14)
par(mar=c(2,4,1,1),mfrow=c(3,1), mgp=c(1.8,0.5,0))
plot(f, type='l', main='CSI500', ylab="Daily price", xaxt="n",xlab='',col="purple4")
axis(1, at=year_pos,labels=year_labels)
plot(as.vector(unname(ret_d500)), type='l', ylab="Daily return", xaxt="n",xlab='year',col="cornflowerblue",ylim=c(-0.1,0.1))
axis(1, at=year_pos,labels=year_labels)
plot(ret_m500, type='l', ylab="Monthly return", xaxt="n",xlab='year',col="blue",ylim=c(-0.02,0.02))
axis(1, at=year_pos,labels=year_labels)
```

```{r}
# 正态性检验----------------------------------------------------------------------------
ps.options(horizontal=F, width=5, height=4, pointsize=12)
par(mar=c(3,3,2,1),mfrow=c(2,3), mgp=c(1.8,0.5,0))

hist(as.vector(unname(ret_d50)), probability=T, nclass=35, xlab='',ylim=c(0,45),
col="chartreuse4",main="SSE50 Daily returns")
x<-seq(-0.5, 0.3, 0.01)
lines(x, dnorm(x, mean(as.vector(unname(ret_d50))), sd(as.vector(unname(ret_d50)))), col="blue")

hist(as.vector(unname(ret_d300)), probability=T, nclass=35, xlab='',ylim=c(0,45),
col="purple4",main="CSI300 Daily returns")
x<-seq(-0.5, 0.3, 0.01)
lines(x, dnorm(x, mean(as.vector(unname(ret_d300))), sd(as.vector(unname(ret_d300)))), col="blue")

hist(as.vector(unname(ret_d500)), probability=T, nclass=35, xlab='',ylim=c(0,45),
col="cyan4",main="CSI500 Daily returns")
x<-seq(-0.5, 0.3, 0.01)
lines(x, dnorm(x, mean(as.vector(unname(ret_d500))), sd(as.vector(unname(ret_d300)))), col="blue")

qqnorm(as.vector(unname(ret_d50)),xlab='Normal quantile', ylab='Quantile of daily returns',
col="brown",ylim=c(-0.1,0.1))
qqline(as.vector(unname(ret_d50)), col="blue")


qqnorm(as.vector(unname(ret_d300)),xlab='Normal quantile', ylab='Quantile of daily returns',
col="brown",ylim=c(-0.1,0.1))
qqline(as.vector(unname(ret_d300)), col="blue")

qqnorm(as.vector(unname(ret_d500)),xlab='Normal quantile', ylab='Quantile of daily returns',
col="brown",ylim=c(-0.1,0.1))
qqline(as.vector(unname(ret_d500)), col="blue")
```

```{r}
adf.test(ret_d50) # 平稳
adf.test(ret_d300) # 平稳
adf.test(ret_d500) # 平稳

adf.test(ret_m50) # 平稳
adf.test(ret_m300) # 平稳
adf.test(ret_m500) # 平稳
```

```{r}
Box.test(ret_d50)
Box.test(ret_d300)
Box.test(ret_d500)

Box.test(ret_m50)
Box.test(ret_m300)
Box.test(ret_m500)
```

```{r,warning=FALSE}
# time series analysis of daily return
#中证500的AR模型
max_lag=15
datanew=ret_d500
N=length(datanew)
b=10
# BIC选择模型阶数
BICs=rep(0,max_lag)
ytrain=datanew[1:(N-b)]
ytest=datanew[(N-b+1):N]

for(p in 0:max_lag){
  fit.ar <- stats::arima(ytrain, order = c(p,0,0),method = "ML")
  BICs[p] <- BIC(fit.ar)
}
p_bic=which.min(BICs)
fit.ar <- stats::arima(ytrain, order = c(p_bic,0,0),method = "ML")
fit.ar
# 白噪声检验
forecast_ar <- forecast(fit.ar,h=b,level=c(95))# h表示向前预测b步
checkresiduals(forecast_ar)

#中证500的ARMA模型
max_lag=5
datanew=ret_d500
N=length(datanew)
b=10 # 先前预测的数量
BICs=rep(0,max_lag)# BIC选择模型阶数
ytrain=datanew[1:(N-b)]
ytest=datanew[(N-b+1):N]

BICs=matrix(0,max_lag,max_lag)
for(p in 0:max_lag){
  for(q in 0:max_lag){
    fit.arma <- stats::arima(ytrain, order = c(p,0,q),method = "ML")
    BICs[p,q] <- BIC(fit.arma)
  }
}
which(BICs==min(BICs),arr.ind = TRUE) # 最后的结果是ARMA(1,1)
fit.arma <- stats::arima(ytrain, order = c(1,0,1),method = "ML")
fit.arma

# 预测
forecast_ar <- forecast(fit.ar,h=b,level=c(95))
forecast_arma <- forecast(fit.arma,h=b,level=c(95))
forecast_mean=meanf(ytrain,h=b) #均值预测
forecast_naive=naive(ytrain,h=b) #朴素预测

# 对结果进行白噪声检验
checkresiduals(forecast_arma)

# 预测精度
accuracy_ar=accuracy(forecast_ar,ytest)[2,]
accuracy_arma=accuracy(forecast_arma,ytest)[2,]
accuracy_mean=accuracy(forecast_mean,ytest)[2,]
accuracy_naive=accuracy(forecast_naive,ytest)[2,]
```
```{r}
# 日收益率的ARMA模型的残差未通过白噪声检验，进一步进行GARCH拟合
spec <- rugarch::ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1, 1)),
                   mean.model = list(armaOrder = c(1, 1)))

# Fit the ARMA-GARCH model
fit <- ugarchfit(spec, data = ytrain)
print(fit)

# Obtain the model residuals
residuals <- residuals(fit)
Box.test(residuals,type="Ljung-Box")

predictions <- ugarchforecast(fit, n.ahead = b)@forecast$seriesFor[, 1]
actual = as.vector(ytest)
# Calculate evaluation metrics
me <- mean((actual - predictions))
rmse <- sqrt(mean((actual - predictions)^2))
mae <- mean(abs(actual - predictions))
```

```{r}
result_csi500=rbind(accuracy_ar[1:3],accuracy_arma[1:3],accuracy_mean[1:3],accuracy_naive[1:3],c(me,rmse,mae))
rownames(result_csi500) = c("AR(1)","ARMA(1,1)","mean","naive","GARCH")
result_csi500
```

```{r,warning=FALSE}
# time series analysis of monthly return
#中证500的AR模型
max_lag=15
datanew=ret_m500
N=length(datanew)
b=6
# BIC选择模型阶数
BICs=rep(0,max_lag)
ytrain=datanew[1:(N-b)]
ytest=datanew[(N-b+1):N]

for(p in 0:max_lag){
  fit.ar <- stats::arima(ytrain, order = c(p,0,0),method = "ML")
  BICs[p] <- BIC(fit.ar)
}
p_bic=which.min(BICs)
fit.ar <- stats::arima(ytrain, order = c(p_bic,0,0),method = "ML")
fit.ar
# 白噪声检验
forecast_ar <- forecast(fit.ar,h=b,level=c(95))# h表示向前预测b步
checkresiduals(forecast_ar)

#中证500的ARMA模型
max_lag=5
datanew=ret_m500
N=length(datanew)
b=6 # 先前预测的数量
BICs=rep(0,max_lag)# BIC选择模型阶数
ytrain=datanew[1:(N-b)]
ytest=datanew[(N-b+1):N]

BICs=matrix(0,max_lag,max_lag)
for(p in 0:max_lag){
  for(q in 0:max_lag){
    fit.arma <- stats::arima(ytrain, order = c(p,0,q),method = "ML")
    BICs[p,q] <- BIC(fit.arma)
  }
}
which(BICs==min(BICs),arr.ind = TRUE) # 最后的结果是ARMA(1,1)
fit.arma <- stats::arima(ytrain, order = c(1,0,1),method = "ML")
fit.arma
# 预测
forecast_ar <- forecast(fit.ar,h=b,level=c(95))
forecast_arma <- forecast(fit.arma,h=b,level=c(95))
forecast_mean=meanf(ytrain,h=b) #均值预测
forecast_naive=naive(ytrain,h=b) #朴素预测
# 对结果进行白噪声检验
checkresiduals(forecast_arma)

# 预测精度
accuracy_ar=accuracy(forecast_ar,ytest)[2,]
accuracy_arma=accuracy(forecast_arma,ytest)[2,]
accuracy_mean=accuracy(forecast_mean,ytest)[2,]
accuracy_naive=accuracy(forecast_naive,ytest)[2,]
# 精度合并起来
# 多种方法预测结果并列在一起
result_csi500_mon=rbind(accuracy_ar[1:3],accuracy_arma[1:3],accuracy_mean[1:3],accuracy_naive[1:3])
rownames(result_csi500_mon) = c("AR(1)","ARMA(1,1)","mean","naive")
result_csi500_mon
```


```{r, warning=FALSE}
# 宏观经济指标--------------------------------
econdata = read.csv("EconData2012-2023.csv")[24:136,]
econdata[,"中国.CGPI.当月同比"] = econdata[,"中国.CGPI.当月同比"]-100

# Convert columns to numeric data type and handle missing values
columns = c("中国.CPI.环比",	"中国.PPI.全部工业品.环比", 
            "中国.M0.同比",	"中国.M1.同比",	"中国.M2.同比",	
            "中国.社会消费品零售总额.当月同比",
            "中国.金融机构.各项贷款余额.同比","中国.公共财政收入.当月值")
df = econdata
df[,columns] <- sapply(df[,columns], as.numeric)
filled_df = zoo::na.approx(df[, columns], method = "linear")

# Create an empty dataframe to store the Box test results
adf_test_results <- data.frame(
  Variable = character(),
  Original = numeric(),
  First_Difference = numeric(),
  Second_Difference = numeric(),
  stringsAsFactors = FALSE
)

# Iterate over each column and calculate the Box test p-values
for (col in colnames(filled_df)) {
  variable <- df[[col]]
  # Remove missing values
  variable <- na.omit(variable)

  adf_test_original <- adf.test(variable)
  adf_test_diff1 <- adf.test(diff(variable))
  adf_test_diff2 <- adf.test(diff(diff(variable)))
  
  # Append the results to the dataframe
  adf_test_results <- rbind(adf_test_results, data.frame(
    Variable = col,
    Original = adf_test_original$p.value,
    First_Difference = adf_test_diff1$p.value
    ,Second_Difference = adf_test_diff2$p.value
  ))
}

# Print the resulting table
print(adf_test_results)
```

```{r}
# Create a correlation matrix
correlation_matrix <- cor(filled_df)
correlation_matrix
# 设置字符编码为中文（简体）
Sys.setlocale("LC_CTYPE", "zh_CN.UTF-8")
par(family = "微软雅黑")
# Create a heatmap of the correlation matrix
heatmap(correlation_matrix, main = "Correlation Heatmap")
```

```{r}
# 执行Johansen协整检验
filled_econdata_j = data.frame(diff(filled_df)[,c("中国.PPI.全部工业品.环比",
                                                  "中国.M0.同比",	
                                                  "中国.金融机构.各项贷款余额.同比")])

# 执行Johansen协整检验
johansen_results <- urca::ca.jo(filled_econdata_j, type = "trace", K = 2)  # K是协整关系的最大阶数

# 查看协整检验结果
summary(johansen_results)
```

```{r}
# 中证500回归结合宏观经济指标—————————————————————————————————————————————————
macro_data <- as.data.frame(cbind(econdata$指标名称[2:nrow(econdata)],
                                  filled_econdata_j[,c("中国.PPI.全部工业品.环比","中国.M0.同比","中国.金融机构.各项贷款余额.同比")],
                                  filled_df[2:nrow(econdata),
                                            c("中国.CPI.环比",
                                              "中国.公共财政收入.当月值")]))
macro_data[,1] = as.Date(macro_data[,1])
colnames(macro_data) = c("Date","PPI.diff","M0.diff","loan.diff","CPI","GovIncome")

df <- macro_data %>% mutate(return=as.vector(unname(ret_m500)))

data_subset <- df[1:(nrow(df)-6),c("PPI.diff","M0.diff","loan.diff","CPI","GovIncome","return")]
model <- lm(return ~ ., data = data_subset)

# View the model summary
summary(model)
```
```{r}
# ME, RMSE, MAE
newdata = df[(nrow(df)-6):nrow(df),]
predictions <- predict(model, newdata)
actual <- newdata$return

# Calculate evaluation metrics
me <- mean((actual - predictions))
rmse <- sqrt(mean((actual - predictions)^2))
mae <- mean(abs(actual - predictions))

result_csi500_mon = rbind(result_csi500_mon,c(me,rmse,mae))
rownames(result_csi500_mon)[5] = "macro_indicators"
result_csi500_mon
```

